/** Options for {@link runPlan}. */
export interface RunPlanOptions {
  /** The feature or release name to substitute into the heading. */
  name?: string;
}

/**
 * Renders the blueprint's canonical Test Plan Markdown template (Part I), with `opts.name`
 * substituted into the heading. Every other section is left as a fill-in-the-blank skeleton for
 * a human or an AI agent to complete.
 */
export function runPlan(opts: RunPlanOptions = {}): string {
  const name = opts.name ?? '[Feature or Release Name]';

  const lines = [
    `## Test Plan: ${name}`,
    '',
    '### 1. Objective',
    'What quality gates must this plan satisfy before shipping?',
    '',
    '### 2. Scope',
    '**In scope:** [list of features, routes, user flows]',
    '**Out of scope:** [explicit exclusions]',
    '',
    '### 3. Test Items',
    '| Item | Type | Priority | Linked Requirement |',
    '|------|------|----------|-------------------|',
    '| User login flow | Smoke + Regression | P1 | ISSUE-101 |',
    '| Password reset email | Regression | P2 | ISSUE-102 |',
    '',
    '### 4. Test Approach',
    '- Smoke suite: 5 critical path checks, run on every deploy',
    '- Selective regression: tag-scoped to changed modules',
    '- AI exploratory: Claude agent given PR diff + feature description',
    '- API contract checks: OpenAPI validation on changed endpoints',
    '',
    '### 5. Test Environment',
    '- URL: [preview_url from CI]',
    '- Browser: Chromium 130+ (Playwright)',
    '- Seed data: [describe fixtures]',
    '',
    '### 6. Entry Criteria',
    '- [ ] Build deploys successfully to preview environment',
    '- [ ] Smoke suite passes (green gate)',
    '- [ ] No open P1 defects blocking scope',
    '',
    '### 7. Exit Criteria',
    '- [ ] 0 open CRITICAL or HIGH defects in scope',
    '- [ ] Smoke suite: 100% pass rate',
    '- [ ] Regression suite: ≥95% pass rate',
    '- [ ] AI exploratory agent reports no blocking issues',
    '- [ ] Coverage: all P1 requirements linked to ≥1 PASS execution',
    '',
    '### 8. Risks & Mitigations',
    '| Risk | Impact | Mitigation |',
    '|------|--------|-----------|',
    '| Flaky auth tests | High | Retry up to 3x; quarantine if flake rate > 10% |',
    '',
    '### 9. Sign-off',
    'Auto-generated by AI QA Platform on PR open. Human review required for CRITICAL failures.',
    '',
  ];

  return lines.join('\n');
}
